# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1/gvoice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/v1/gvoice.proto',
  package='',
  syntax='proto2',
  serialized_options=b'Z,github.com/kingcobra2468/cot/internal/gvoice',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x61pi/v1/gvoice.proto\"^\n\x0eSendSMSRequest\x12\x1b\n\x13gvoice_phone_number\x18\x01 \x02(\t\x12\x1e\n\x16recipient_phone_number\x18\x02 \x02(\t\x12\x0f\n\x07message\x18\x03 \x02(\t\"3\n\x0fSendSMSResponse\x12\x0f\n\x07success\x18\x01 \x02(\x08\x12\x0f\n\x05\x65rror\x18\x02 \x01(\t:\x00\"6\n\x17\x46\x65tchContactListRequest\x12\x1b\n\x13gvoice_phone_number\x18\x01 \x02(\t\"]\n\x18\x46\x65tchContactListResponse\x12\x0f\n\x07success\x18\x01 \x02(\x08\x12\x0f\n\x05\x65rror\x18\x02 \x01(\t:\x00\x12\x1f\n\x17recipient_phone_numbers\x18\x03 \x03(\t\"\x1b\n\x19\x46\x65tchGVoiceNumbersRequest\"\\\n\x1a\x46\x65tchGVoiceNumbersResponse\x12\x0f\n\x07success\x18\x01 \x02(\x08\x12\x0f\n\x05\x65rror\x18\x02 \x01(\t:\x00\x12\x1c\n\x14gvoice_phone_numbers\x18\x03 \x03(\t\"r\n\x1a\x46\x65tchContactHistoryRequest\x12\x1b\n\x13gvoice_phone_number\x18\x01 \x02(\t\x12\x1e\n\x16recipient_phone_number\x18\x02 \x02(\t\x12\x17\n\x0cnum_messages\x18\x03 \x02(\x04:\x01\x30\"_\n\x1b\x46\x65tchContactHistoryResponse\x12\x0f\n\x07success\x18\x01 \x02(\x08\x12\x0f\n\x05\x65rror\x18\x02 \x01(\t:\x00\x12\x1e\n\x08messages\x18\x03 \x03(\x0b\x32\x0c.MessageNode\"J\n\x0bMessageNode\x12\x11\n\ttimestamp\x18\x01 \x02(\x04\x12\x18\n\x10message_contents\x18\x02 \x02(\t\x12\x0e\n\x06source\x18\x03 \x02(\x08\x32\xa2\x02\n\x06GVoice\x12.\n\x07SendSMS\x12\x0f.SendSMSRequest\x1a\x10.SendSMSResponse\"\x00\x12G\n\x0eGetContactList\x12\x18.FetchContactListRequest\x1a\x19.FetchContactListResponse\"\x00\x12M\n\x10GetGVoiceNumbers\x12\x1a.FetchGVoiceNumbersRequest\x1a\x1b.FetchGVoiceNumbersResponse\"\x00\x12P\n\x11GetContactHistory\x12\x1b.FetchContactHistoryRequest\x1a\x1c.FetchContactHistoryResponse\"\x00\x42.Z,github.com/kingcobra2468/cot/internal/gvoice'
)




_SENDSMSREQUEST = _descriptor.Descriptor(
  name='SendSMSRequest',
  full_name='SendSMSRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gvoice_phone_number', full_name='SendSMSRequest.gvoice_phone_number', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recipient_phone_number', full_name='SendSMSRequest.recipient_phone_number', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='SendSMSRequest.message', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=117,
)


_SENDSMSRESPONSE = _descriptor.Descriptor(
  name='SendSMSResponse',
  full_name='SendSMSResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='SendSMSResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='SendSMSResponse.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=170,
)


_FETCHCONTACTLISTREQUEST = _descriptor.Descriptor(
  name='FetchContactListRequest',
  full_name='FetchContactListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gvoice_phone_number', full_name='FetchContactListRequest.gvoice_phone_number', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=226,
)


_FETCHCONTACTLISTRESPONSE = _descriptor.Descriptor(
  name='FetchContactListResponse',
  full_name='FetchContactListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='FetchContactListResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='FetchContactListResponse.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recipient_phone_numbers', full_name='FetchContactListResponse.recipient_phone_numbers', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=321,
)


_FETCHGVOICENUMBERSREQUEST = _descriptor.Descriptor(
  name='FetchGVoiceNumbersRequest',
  full_name='FetchGVoiceNumbersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=350,
)


_FETCHGVOICENUMBERSRESPONSE = _descriptor.Descriptor(
  name='FetchGVoiceNumbersResponse',
  full_name='FetchGVoiceNumbersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='FetchGVoiceNumbersResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='FetchGVoiceNumbersResponse.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gvoice_phone_numbers', full_name='FetchGVoiceNumbersResponse.gvoice_phone_numbers', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=444,
)


_FETCHCONTACTHISTORYREQUEST = _descriptor.Descriptor(
  name='FetchContactHistoryRequest',
  full_name='FetchContactHistoryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gvoice_phone_number', full_name='FetchContactHistoryRequest.gvoice_phone_number', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recipient_phone_number', full_name='FetchContactHistoryRequest.recipient_phone_number', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_messages', full_name='FetchContactHistoryRequest.num_messages', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=560,
)


_FETCHCONTACTHISTORYRESPONSE = _descriptor.Descriptor(
  name='FetchContactHistoryResponse',
  full_name='FetchContactHistoryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='FetchContactHistoryResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='FetchContactHistoryResponse.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='messages', full_name='FetchContactHistoryResponse.messages', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=562,
  serialized_end=657,
)


_MESSAGENODE = _descriptor.Descriptor(
  name='MessageNode',
  full_name='MessageNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='MessageNode.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message_contents', full_name='MessageNode.message_contents', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source', full_name='MessageNode.source', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=659,
  serialized_end=733,
)

_FETCHCONTACTHISTORYRESPONSE.fields_by_name['messages'].message_type = _MESSAGENODE
DESCRIPTOR.message_types_by_name['SendSMSRequest'] = _SENDSMSREQUEST
DESCRIPTOR.message_types_by_name['SendSMSResponse'] = _SENDSMSRESPONSE
DESCRIPTOR.message_types_by_name['FetchContactListRequest'] = _FETCHCONTACTLISTREQUEST
DESCRIPTOR.message_types_by_name['FetchContactListResponse'] = _FETCHCONTACTLISTRESPONSE
DESCRIPTOR.message_types_by_name['FetchGVoiceNumbersRequest'] = _FETCHGVOICENUMBERSREQUEST
DESCRIPTOR.message_types_by_name['FetchGVoiceNumbersResponse'] = _FETCHGVOICENUMBERSRESPONSE
DESCRIPTOR.message_types_by_name['FetchContactHistoryRequest'] = _FETCHCONTACTHISTORYREQUEST
DESCRIPTOR.message_types_by_name['FetchContactHistoryResponse'] = _FETCHCONTACTHISTORYRESPONSE
DESCRIPTOR.message_types_by_name['MessageNode'] = _MESSAGENODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendSMSRequest = _reflection.GeneratedProtocolMessageType('SendSMSRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDSMSREQUEST,
  '__module__' : 'api.v1.gvoice_pb2'
  # @@protoc_insertion_point(class_scope:SendSMSRequest)
  })
_sym_db.RegisterMessage(SendSMSRequest)

SendSMSResponse = _reflection.GeneratedProtocolMessageType('SendSMSResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDSMSRESPONSE,
  '__module__' : 'api.v1.gvoice_pb2'
  # @@protoc_insertion_point(class_scope:SendSMSResponse)
  })
_sym_db.RegisterMessage(SendSMSResponse)

FetchContactListRequest = _reflection.GeneratedProtocolMessageType('FetchContactListRequest', (_message.Message,), {
  'DESCRIPTOR' : _FETCHCONTACTLISTREQUEST,
  '__module__' : 'api.v1.gvoice_pb2'
  # @@protoc_insertion_point(class_scope:FetchContactListRequest)
  })
_sym_db.RegisterMessage(FetchContactListRequest)

FetchContactListResponse = _reflection.GeneratedProtocolMessageType('FetchContactListResponse', (_message.Message,), {
  'DESCRIPTOR' : _FETCHCONTACTLISTRESPONSE,
  '__module__' : 'api.v1.gvoice_pb2'
  # @@protoc_insertion_point(class_scope:FetchContactListResponse)
  })
_sym_db.RegisterMessage(FetchContactListResponse)

FetchGVoiceNumbersRequest = _reflection.GeneratedProtocolMessageType('FetchGVoiceNumbersRequest', (_message.Message,), {
  'DESCRIPTOR' : _FETCHGVOICENUMBERSREQUEST,
  '__module__' : 'api.v1.gvoice_pb2'
  # @@protoc_insertion_point(class_scope:FetchGVoiceNumbersRequest)
  })
_sym_db.RegisterMessage(FetchGVoiceNumbersRequest)

FetchGVoiceNumbersResponse = _reflection.GeneratedProtocolMessageType('FetchGVoiceNumbersResponse', (_message.Message,), {
  'DESCRIPTOR' : _FETCHGVOICENUMBERSRESPONSE,
  '__module__' : 'api.v1.gvoice_pb2'
  # @@protoc_insertion_point(class_scope:FetchGVoiceNumbersResponse)
  })
_sym_db.RegisterMessage(FetchGVoiceNumbersResponse)

FetchContactHistoryRequest = _reflection.GeneratedProtocolMessageType('FetchContactHistoryRequest', (_message.Message,), {
  'DESCRIPTOR' : _FETCHCONTACTHISTORYREQUEST,
  '__module__' : 'api.v1.gvoice_pb2'
  # @@protoc_insertion_point(class_scope:FetchContactHistoryRequest)
  })
_sym_db.RegisterMessage(FetchContactHistoryRequest)

FetchContactHistoryResponse = _reflection.GeneratedProtocolMessageType('FetchContactHistoryResponse', (_message.Message,), {
  'DESCRIPTOR' : _FETCHCONTACTHISTORYRESPONSE,
  '__module__' : 'api.v1.gvoice_pb2'
  # @@protoc_insertion_point(class_scope:FetchContactHistoryResponse)
  })
_sym_db.RegisterMessage(FetchContactHistoryResponse)

MessageNode = _reflection.GeneratedProtocolMessageType('MessageNode', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGENODE,
  '__module__' : 'api.v1.gvoice_pb2'
  # @@protoc_insertion_point(class_scope:MessageNode)
  })
_sym_db.RegisterMessage(MessageNode)


DESCRIPTOR._options = None

_GVOICE = _descriptor.ServiceDescriptor(
  name='GVoice',
  full_name='GVoice',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=736,
  serialized_end=1026,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendSMS',
    full_name='GVoice.SendSMS',
    index=0,
    containing_service=None,
    input_type=_SENDSMSREQUEST,
    output_type=_SENDSMSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetContactList',
    full_name='GVoice.GetContactList',
    index=1,
    containing_service=None,
    input_type=_FETCHCONTACTLISTREQUEST,
    output_type=_FETCHCONTACTLISTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetGVoiceNumbers',
    full_name='GVoice.GetGVoiceNumbers',
    index=2,
    containing_service=None,
    input_type=_FETCHGVOICENUMBERSREQUEST,
    output_type=_FETCHGVOICENUMBERSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetContactHistory',
    full_name='GVoice.GetContactHistory',
    index=3,
    containing_service=None,
    input_type=_FETCHCONTACTHISTORYREQUEST,
    output_type=_FETCHCONTACTHISTORYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GVOICE)

DESCRIPTOR.services_by_name['GVoice'] = _GVOICE

# @@protoc_insertion_point(module_scope)
