# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.v1 import gvoice_pb2 as api_dot_v1_dot_gvoice__pb2


class GVoiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendSMS = channel.unary_unary(
                '/GVoice/SendSMS',
                request_serializer=api_dot_v1_dot_gvoice__pb2.SendSMSRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_gvoice__pb2.SendSMSResponse.FromString,
                )
        self.GetContactList = channel.unary_unary(
                '/GVoice/GetContactList',
                request_serializer=api_dot_v1_dot_gvoice__pb2.FetchContactListRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_gvoice__pb2.FetchContactListResponse.FromString,
                )
        self.GetGVoiceNumbers = channel.unary_unary(
                '/GVoice/GetGVoiceNumbers',
                request_serializer=api_dot_v1_dot_gvoice__pb2.FetchGVoiceNumbersRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_gvoice__pb2.FetchGVoiceNumbersResponse.FromString,
                )
        self.GetContactHistory = channel.unary_unary(
                '/GVoice/GetContactHistory',
                request_serializer=api_dot_v1_dot_gvoice__pb2.FetchContactHistoryRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_gvoice__pb2.FetchContactHistoryResponse.FromString,
                )


class GVoiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendSMS(self, request, context):
        """Sends a message to the recipient.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContactList(self, request, context):
        """Gets the contact list for a given GVoice account.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGVoiceNumbers(self, request, context):
        """Gets all GVoice numbers that are accessible/ready to be used by the service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContactHistory(self, request, context):
        """Fetches the text-message history between a contact on a given GVoice account.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GVoiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendSMS': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSMS,
                    request_deserializer=api_dot_v1_dot_gvoice__pb2.SendSMSRequest.FromString,
                    response_serializer=api_dot_v1_dot_gvoice__pb2.SendSMSResponse.SerializeToString,
            ),
            'GetContactList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContactList,
                    request_deserializer=api_dot_v1_dot_gvoice__pb2.FetchContactListRequest.FromString,
                    response_serializer=api_dot_v1_dot_gvoice__pb2.FetchContactListResponse.SerializeToString,
            ),
            'GetGVoiceNumbers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGVoiceNumbers,
                    request_deserializer=api_dot_v1_dot_gvoice__pb2.FetchGVoiceNumbersRequest.FromString,
                    response_serializer=api_dot_v1_dot_gvoice__pb2.FetchGVoiceNumbersResponse.SerializeToString,
            ),
            'GetContactHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContactHistory,
                    request_deserializer=api_dot_v1_dot_gvoice__pb2.FetchContactHistoryRequest.FromString,
                    response_serializer=api_dot_v1_dot_gvoice__pb2.FetchContactHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GVoice', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GVoice(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendSMS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GVoice/SendSMS',
            api_dot_v1_dot_gvoice__pb2.SendSMSRequest.SerializeToString,
            api_dot_v1_dot_gvoice__pb2.SendSMSResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetContactList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GVoice/GetContactList',
            api_dot_v1_dot_gvoice__pb2.FetchContactListRequest.SerializeToString,
            api_dot_v1_dot_gvoice__pb2.FetchContactListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGVoiceNumbers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GVoice/GetGVoiceNumbers',
            api_dot_v1_dot_gvoice__pb2.FetchGVoiceNumbersRequest.SerializeToString,
            api_dot_v1_dot_gvoice__pb2.FetchGVoiceNumbersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetContactHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GVoice/GetContactHistory',
            api_dot_v1_dot_gvoice__pb2.FetchContactHistoryRequest.SerializeToString,
            api_dot_v1_dot_gvoice__pb2.FetchContactHistoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
